<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=1, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="bootstrap.min.css">
  </link>
  <title>{Titulo}</title>
</head>

<body>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Cargo</td>
        <th scope="col">Permissões</th>
      </tr>
    </thead>
    <tbody>
      [require "teste.phtml"]
    </tbody>
  </table>

</body>

</html>