[foreach user as k => v {
<tr>
  <th scope="row">{k}</th>
  <td scope="row">{v.name}</td>
  <td scope="row">
    [if(v.acess != ""){
    {v.acess}
    }]
    [else{
    Nenhum
    }]
  </td>
  <td scope="row">

    [if(v.acess == "Admin" && !(1 == 1)){
    Todas as Permissões
    }]
    [else if (v.acess == "Gerente"){
    Escrever - Visualizar - Postar
    }]
    [elseif (v.acess == "Cliente"){
    Visualizar
    }]
    [else {
    Nada
    }]

  </td>
</tr>

}]